<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\ValidationException;


class ApiRequest extends FormRequest
{
    public function failedValidation(Validator $validator)
    {
        throw new ValidationException($validator, response()->json([
            'error'=>[
                'code' => 422,
                'message' => 'Validation error',
                'errors' => $validator->errors()
            ]
        ], 422)); // TODO: Change the autogenerated stub
    }
}
